[workspace]
resolver = "2"
members = [
    # The actual library crate
    "sdk",

    "async-split",
    "async-split-macro",

    # Helper program, not published
    "sniff",

    # Example related libraries, not published
    "examples-shared",
    "examples/*", "async-split",
]
