[package]
name = "async-split"
version = "0.1.0"
edition = "2021"

[features]
async = ["async-split-macro/async"]

[dependencies]
async-split-macro = { path = "../async-split-macro" }
crossbeam-channel = "0.5"